name: "[Job] Manage Image Tags and Environment Workspaces"

on:
  workflow_call:
    inputs:
      changes_detected:
        description: 'Boolean value for changes detected in /app from main'
        required: true
        type: string
    outputs:
      version_tag:
        description: "Docker Image Tag"
        value: ${{ jobs.consolidate_tags.outputs.docker_tag }}
      environment_workspace_name:
        description: "Terraform Environment Workspace Name"
        value: ${{ jobs.generate_environment_workspace_name.outputs.environment_workspace_name }}

jobs:
  create_tags:
    if : ${{ inputs.changes_detected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Extract branch name
        id: extract_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            branch=${{ github.head_ref }}
            branch=${branch//-}
            branch=${branch//_}
            branch=${branch//\/}
            echo BRANCH_NAME=${branch} >> $GITHUB_ENV
          fi
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: minor
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true
    outputs:
      docker_tag: ${{ steps.bump_version.outputs.tag }}

  consolidate_tags:
    needs: [
      create_tags,
      ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: consolidate tags
        id: consolidate_tags
        run: |
          if ${{needs.create_tags.result == 'skipped'}}; then
            echo "tag=${{needs.pull_tags.outputs.docker_tag}}" >> $GITHUB_OUTPUT
            echo '### Tag for deployment ${{needs.pull_tags.outputs.docker_tag}} pulled from ${{needs.pull_tags.outputs.tag_from}}' >> $GITHUB_STEP_SUMMARY
          else
            echo "tag=${{needs.create_tags.outputs.docker_tag}}" >> $GITHUB_OUTPUT
            echo '### New tag for deployment ${{needs.create_tags.outputs.docker_tag}}' >> $GITHUB_STEP_SUMMARY
          fi
    outputs:
      docker_tag: ${{ steps.consolidate_tags.outputs.tag }}
