name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: write
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: create_tags
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      checkout_tag: ${{ github.head_ref }}
      branch_name: ${{ github.head_ref }}

  pr_deploy:
      name: ${{ needs.create_tags.outputs.environment_workspace_name }} PR Environment Deploy
      if: always() &&
        (needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'skipped')
      needs: [
        create_tags,
        docker_build_scan_push,
      ]
      uses: ./.github/workflows/terraform_environment_job.yml
      with:
        workspace_name: ${{ needs.create_tags.outputs.environment_workspace_name }}
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
      # secrets:
        # ssh_deploy_key: ${{ secrets.OPG_MODERNISING_LPA_DEPLOY_KEY_PRIVATE_KEY }}
        # github_access_token: ${{ secrets.GITHUB_TOKEN }}

  end_of_pr_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    needs: [
      docker_build_scan_push,
      pr_deploy,
    ]
    if: always()
    steps:
      - name: End of PR Workflow
        run: |
          echo "End of workflow"
