name: "Path To Live"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: create_tags
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      checkout_tag: ${{ github.head_ref }}
      branch_name: ${{ github.head_ref }}

  end_of_pr_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    needs: docker_build_scan_push
    if: always()
    steps:
      - name: End of PR Workflow
        run: |
          echo "End of workflow"
