name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: write
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: create_tags
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
      checkout_tag: ${{ github.head_ref }}
      branch_name: ${{ github.head_ref }}

  terraform_account_workflow_development:
    name: TF Plan Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: development
      oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  pr_deploy:
      name: ${{ needs.create_tags.outputs.environment_workspace_name }} PR Environment Deploy
      needs: [
        create_tags,
        docker_build_scan_push,
      ]
      uses: ./.github/workflows/terraform_environment_job.yml
      secrets:
        ssh_deploy_key: ${{ secrets.MRLPA_MC_DEPLOY_KEY_PRIVATE_KEY }}
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        workspace_name: ${{ needs.create_tags.outputs.environment_workspace_name }}
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
        oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  test_environment:
    name: ${{ needs.create_tags.outputs.environment_workspace_name }} PR Environment Test
    needs: [pr_deploy]
    uses: ./.github/workflows/test.yml
    with:
      environment_fqdn: ${{ needs.pr_deploy.outputs.environment_fqdn }}
      environment_config_json: ${{ needs.pr_deploy.outputs.environment_config_json }}
      # TODO: use reduced role for ingress management here
      oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  always_remove_ingress:
    name: Remove CI ingress from environment
    if: always()
    uses: ./.github/workflows/remove_ingress_job.yml
    needs: [ui_tests_pr_env, pr_deploy]
    with:
      environment_config_json: ${{ needs.pr_deploy.outputs.environment_config_json }}
      oidc_role_arn: arn:aws:iam::679638075911:role/opg-mrlpa-mc-github-actions-ci-terraform-development

  end_of_pr_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    needs: [
      docker_build_scan_push,
      pr_deploy,
      test_environment,
    ]
    if: always()
    steps:
      - name: End of PR Workflow
        run: |
          echo "End of workflow"
